services:
  - type: web
    name: binder-keepalive
    env: python
    plan: free
    buildCommand: pip install -r binder-keepalive/requirements.txt
    startCommand: python binder-keepalive/keepalive.py
    envVars: []
    autoDeploy: true
    ports:
      - port: 10000
      
