services:
  - type: web
    name: binder-keepalive
    env: python
    buildCommand: pip install -r binder-keepalive/requirements.txt
    startCommand: python binder-keepalive/keepalive.py
    autoDeploy: true
    
